INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES ('Adams', 'Roy');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES ('Lando', 'Norris');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES ('Danial', 'Ricardo');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES ('Lewis', 'Hamiliton');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES ('Bottas', 'Roy');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES ('Max', 'Verstappen');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME) VALUES ('Sergio', 'Peres');
